version: 0.0
os: linux
files:
  - source: docker-compose.prod.yml
    destination: /opt/chess-app/
  - source: views/
    destination: /opt/chess-app/views/
  - source: public/
    destination: /opt/chess-app/public/

permissions:
  - object: /opt/chess-app/chess-app-binary
    mode: "0755"
    owner: ec2-user
    group: ec2-user
  - object: /opt/chess-app/
    mode: "0755"
    owner: ec2-user
    group: ec2-user
    type:
      - directory

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root