services:
  web:
    container_name: webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: on-failure
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: mypassword
      REDIS_DATABASES: 16
      REDIS_MAXMEMORY: 512mb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      
volumes:
  pgdata:
  redis-data: