apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Name }}
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

    
