apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: web
  ports:
  - port: {{ .Values.ginApp.port }}
    targetPort: {{ .Values.ginApp.port }}
  type: ClusterIP
